name: Build GameMaker Game

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: DESKTOP-PDVBF6B
    runs-on: [self-hosted, Windows]

    steps:
    - name: Run PowerShell script with ExecutionPolicy Bypass
      run: powershell -ExecutionPolicy Bypass -Command "echo 'Execution policy bypassed successfully'"
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GameMaker build environment
      run: |
        echo Setting up GameMaker environment
        mkdir build

    - name: Build Game
      run: |
        "C:\Program Files\GameMaker\GameMaker.exe" ^
        --compile ^
        --project "%GITHUB_WORKSPACE%\MyGame.yyp" ^
        --output "%GITHUB_WORKSPACE%\build" ^
        --runtime "C:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-2024.13.1.242" ^
        --target Windows ^
        --config Default ^
        --v
